package edu.grinnell.csc207.soundsofsorting.sorts;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import edu.grinnell.csc207.soundsofsorting.sortevents.*;

/**
 * A collection of sorting algorithms.
 * Most of this file of the project comes from the sorting lab done in class.
 */
public class Sorts {
    /**
     * Swaps indices <code>i</code> and <code>j</code> of array <code>arr</code>.
     * @param <T> the carrier type of the array
     * @param arr the array to swap
     * @param i the first index to swap
     * @param j the second index to swap
     */
    public static <T> void swap(T[] arr, int i, int j) {
        T tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
    }

    /**
     * Sorts the array according to the bubble sort algorithm:
     * <pre>
     * [ unprocessed | i largest elements in order ]
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return List<SortEvent<Integer>> the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> bubbleSort(T[] arr) {
        
        List<SortEvent<Integer>> events = new ArrayList<>();

        // 2 for loops - one element gets added to the right side (largest elements in order) on each overall
        // iteration which consists of going through the entire unprocessed array using the nested liip
        for(int j = 0; j < arr.length-1; j++) {
            for(int i = 0; i < arr.length - 1 - j; i++){

                // New compare event added
                events.add(new CompareEvent<>(i, i + 1));

                // If element at i is greater than the next one, swap takes place
                if(arr[i].compareTo(arr[i + 1]) > 0){

                    // Swap event added
                    events.add(new SwapEvent<>(i, i + 1));
                    swap(arr, i, i + 1);
                }
            }
        }

        return events;

    }

    /**
     * Sorts the array according to the selection sort algorithm:
     * <pre>
     * [ i smallest elements in order | unprocessed ]
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return List<SortEvent<Integer>> the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> selectionSort(T[] arr) {
        
        List<SortEvent<Integer>> events = new ArrayList<>();

        // For each iteration, an element gets added to the left side i.e. the smallest elements in order
        // Each iteration consists of going through the unproccessed region of array and finding the index of 
        // something smaller than the index of current min
        // using nested loop
        for(int i = 0; i<arr.length; i++){

            // Min is assigned to i (index for outer loop)
            int min = i;

            // For loop on rest of elements (unprocessed)
            for (int j = i+1; j<arr.length; j++){

                // New compare event added to events list
                events.add(new CompareEvent<>(min, j));

                if(arr[min].compareTo(arr[j]) > 0){
                    // min set to index j 
                    min = j;
                }
            }

            // Swap event added which swaps the new min found and the old min.
            events.add(new SwapEvent<>(min, i));
            swap(arr, min, i);
        }

        return events;
    }

    /**
     * Sorts the array according to the insertion sort algorithm:
     * <pre>
     * [ i elements in order | unprocessed ] 
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return List<SortEvent<Integer>> the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> insertionSort(T[] arr) {
        
        List<SortEvent<Integer>> events = new ArrayList<>();

        // First element considered sorted, so we start from the 2nd element (on index 1)
        for(int i = 1; i < arr.length; i++){

            // Inner for loop which starts at i and goes down
            for(int j = i; j > 0; j--){

                // New compare event added
                events.add(new CompareEvent<>(j, j - 1));

                // If element at j is greater than the previous element, we break out
                if(arr[j].compareTo(arr[j-1]) > 0) {
                    break;

                // If not, we swap them and then the for loop runs again till j reaches 0 or its position is found
                // so that swaps keep occuring till j finds its correct position
                } else {

                    // New swap event added
                    events.add(new SwapEvent<>(j, j - 1));
                    swap(arr, j, j-1);
                }
            }
        }

        return events;

    }

    /**
     * Sorts the array according to the merge sort algorithm using the helper function mergehelper
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return List<SortEvent<Integer>> the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> mergeSort(T[] arr) {
        
        // Creating the copy array used to hold the sorted elements
        T[] copy = Arrays.copyOf(arr, arr.length);
        // Events list created
        List<SortEvent<Integer>> events = new ArrayList<>();
        // Calling the helper function using start as 0 and end as arr.length
        mergehelper(arr, copy, 0, arr.length, events);
        return events;

    }

    /**
     * Sorts the array according to the quick sort algorithm using helper funciton, quickhelper
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> quickSort(T[] arr) {

        // Events list thats passed into the helper function
        List<SortEvent<Integer>> events = new ArrayList<>();

        // The helper function called with initial start as 0, and end as arr.length -1
        // Visually, the pointers need to start at either end of the array and this takes care of that
        quickhelper(arr, 0, arr.length - 1, events);
        return events;

    }


    /**
     * Helper function used to sort the array according to the quick sort algorithm:
     * Unlike the actual mergesort function, this function takes the array to be sorted,
     * and start and end values for indices of the array (useful in
     * dividing it through the recursive calls) and the List of events that we fill as we go through the sort
     * 
     * <ol>
     * <li>Sort the left half to be smaller than pivot
     * <li>Sort the right half of the array to be greater than chosen pivot
     * <li>Recursively do the same for each half itself
     * </ol>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @param start integer index for start value of the subarray we look at
     * @param end integer index for end value of the subarray we look at
     * @param events the list of events that occur during the sort
     */

    public static <T extends Comparable<? super T>> void quickhelper(T[] arr, int start, int end,
        List<SortEvent<Integer>> events ){

        // if we reach base case, or if indices aern't valid
        if (end - start <= 0){
            return;
        }

        // Last element of array set as random pivot
        T pivot = arr[end];

        // Setting i as start
        int i = start;
        for (int j = start; j < end; j++){
            // New compare event added to events list
            events.add(new CompareEvent<>(j, end));

            // If j is smaller than pivot, it is swapped with element at i which is set as start
            // and i is incremented
            // (to send it to the left hand side of the array smaller than pivot)
            if (arr[j].compareTo(pivot) <= 0){
                // Swap event added
                events.add(new SwapEvent<>(j, i));
                swap(arr, j, i);

                // Updating i manually inside j's while loop
                i++;
            }

            // This ensures that elements before the final i we get by end of loop are smaller than pivot
            // and every element to the left is bigger
            
        }

        // If i doesnt reach end, the element at end and the element at i are swapped 
        // element at end is the pivot and it will come in the middle
        if (i != end){
            events.add(new SwapEvent<>(i, end));
            swap(arr, i, end);
        }

        // Recursive calls from start to i - 1(first half) and from i + 1 to end
        quickhelper(arr, start, i - 1, events);
        quickhelper(arr, i + 1, end, events);
        
    }


    /**
     * Helper function used to sort the array according to the merge sort algorithm:
     * Unlike the actual mergesort function, this function takes the array to be sorted,
     * a copy of that array which is the array we update in correct order/sorted fashion 
     * and start and end values for indices of the array (useful in
     * dividing it through the recursive calls) and the List of events that we fill as we go through the sort
     * 
     * <ol>
     * <li>Sort the left half of the array recursively.</li>
     * <li>Sort the right half of the array recursively.</li>
     * <li>Merge the two sorted halves into a sorted whole.</li>
     * </ol>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @param copy another array which is changed through the recursive levels and arranged in sorted fashion
     * @param start integer index for start value of the subarray we look at
     * @param end integer index for end value of the subarray we look at
     * @param events the list of events that occur during the sort
     */

    public static <T extends Comparable<? super T>> void mergehelper(T[] arr, T[] copy, int start, int end,
    List<SortEvent<Integer>> events) {

        // If there is only one element in the array, no further recursive calls, we return
        if (start == end - 1){
            return;
        }

        // Dividing the array into 2 halves
        int mid = (end + start)/2;

        // Recursively sorting first half and second half
        mergehelper(arr, copy, start, mid, events);
        mergehelper(arr, copy, mid, end, events);

        // We use 3 indices for the merge algorithm.
        // i represents the index for sorted first half array
        // j represents index for sorted second half array
        // k represents index for copy array (i.e. the array we fill in)
        int i = start;
        int j = mid;
        int k = start;

        // Checking if i and j are less than those subarray lengths (not actually declared, this is checked within the main array)
        while (i < mid && j < end){

            // Comparing the first elements of both the sorted halves of the array
            // Whichever is greater is put in as the element at k index of copy array
            // k is incremented and the index for the array used to fill in copy array is incremente
            
            // New omparison event entered into events array
            events.add(new CompareEvent<>(i, j));
            if (((T)arr[i]).compareTo((T)arr[j]) < 0){
                copy[k]=arr[i];
                k++;
                i++;
            } else {
                copy[k]=arr[j];
                k++;
                j++;
            }

        }

        // This is to fill copy array up with sorted elements from whichever half is longer 
        // (i.e. for whichever half elements still remain after the above loop)
        while (i < mid){
            copy[k]=arr[i];
            k++;
            i++;
        }

        while (j < end){
            copy[k]=arr[j];
            k++;
            j++;
        }

        // We copy over elements from copy array to main array
        for (int m = start; m < end; m++){

            arr[m] = copy[m];
            // New Copy event entered into events array
            events.add((SortEvent<Integer>) (SortEvent<?>) new CopyEvent<T>(m, copy[m]));

        }



    }


    /**
     * Gnome Sort works by building a sorted list one element at a time, getting each item to the 
     * proper place in a series of swaps. Basically, we look at the element at our index and the previous one; 
     * if they are in the right order, we move the index forward, otherwise, we swap them and step one index backwards.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> gnomeSort(T[] arr) {

        // Events list that keeps track of the sorting events
        List<SortEvent<Integer>> events = new ArrayList<>();

        // Initializing the index variable for the while loop traversal
        int i = 1;

        // The loop goes on till the index reaches the end of the array
        while (i < arr.length){

            // New comparison event entered into events array
            events.add(new CompareEvent<>(i, i - 1));

            // If index is 0 or if the element at that index is greater than/equal to the element at the index before,
            // we simply increment the index and move on
            if (i == 0 || arr[i].compareTo(arr[i-1]) >= 0){
                i+=1;

            // If not, we swap the elements at the index of the array and the element at the index before
            } else {

                // Adding a new swap event to the events list
                events.add(new SwapEvent<>(i, i - 1));

                // Swapping the elements using our helper function, swap
                swap(arr, i, i-1);

                // We decrease the index after the swap
                i-=1;
            }

        }

        // Returning the events list
        return events;

    }

    /**
     * Sorts the array according to the list of events during that sort
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @param events the list of events that will be applied to the array to sort it
     * @return void
     */
    public static <T> void eventSort(T[] l, List<SortEvent<T>> events){

        for (int i = 0; i < events.size(); i++){
            events.get(i).apply(l);
        }

    }

}
